#!/usr/bin/env python3
"""Compile the coded bills into the file the dashboard reads.

  python3 pipeline/compile.py

Reads  coding/coded/*.json   (the double-coded, adjudicated entries)
       data/bills-2026.js    (display info: state, description, status)
       data/legiscan.js      (live status — decides what counts as enacted)
       data/bills.js         (existing duty-hour table + header, preserved)
Writes data/bills.js

Mechanical merge, no judgment. What gets excluded, and why:
  - entries with duplicateOf        — companion vehicles; the law is counted once
  - bills not enacted               — dataset says enacted=false AND LegiScan
                                      status is not Passed (so post-spreadsheet
                                      enactments like CA AB 1651 stay in)
Validation fails loudly: unknown duty keys, unknown families, unsourced params.
"""
import json, glob, pathlib, re, sys, collections

ROOT = pathlib.Path(__file__).resolve().parent.parent

FAM = {
    "chatbot-safeguards": ("Chatbot safeguards", "Disclosure, crisis protocols, age gates, content guardrails for conversational AI"),
    "mental-health-practice": ("AI in mental-health practice", "Consent, supervision, and limits on AI in therapy"),
    "insurance-adm": ("AI in insurance decisions", "Human review and disclosure for coverage/prior-auth decisions"),
    "adm-governance": ("Automated decision governance", "Risk programs, assessments, notices for consequential decisions"),
    "frontier-safety": ("Frontier model safety", "Safety frameworks, audits, incident reporting for large developers"),
    "provenance-transparency": ("Provenance & transparency", "Watermarking, detection tools, AI-content labeling"),
    "likeness-rights": ("Likeness & digital replicas", "Consent duties for AI imitations of real people"),
    "ai-crimes": ("Criminal prohibitions", "NCII, CSAM, fraud, deepfake crimes — bind individuals"),
    "election-disclosure": ("Election AI disclosure", "Labels on AI content in political communications"),
    "pricing-competition": ("Algorithmic pricing & competition", "Limits on surveillance pricing and price coordination"),
    "privacy-data": ("Privacy & data (AI provisions)", "ADM opt-outs, profiling assessments, minors' data"),
    "workforce": ("Workforce protections", "Worker notice and retaliation protections around AI"),
    "healthcare-clinical": ("AI in clinical care", "Limits on AI in medical practice and licensure"),
    "professional-services": ("Licensed professions", "AI rules in exams and professional practice"),
    "public-sector": ("Government AI use", "Agency inventories, procurement, programs — bind the state"),
    "education-k12": ("Schools & curriculum", "AI literacy, school policies — bind schools"),
    "definitions-only": ("Definitions only", "Defines terms; imposes no duties"),
    "data-centers": ("Data centers", "AI-infrastructure siting, energy, credits"),
}

HEADER = """// CODED DATASET — generated by pipeline/compile.py from coding/coded/. Do not edit by hand.
// Every param and exposure value is anchored to the quoted provision in `sources`.
// Full records (dutySources, flags, confidence, resolution) live in coding/coded/.
// Excluded from the model: duplicate companion vehicles (the law is counted once)
// and bills passed by only one chamber. Duty-hour blocks are estimates for the
// average AI model, pending citation to published burden figures. Reuse and the
// federal baseline derive from params in app.js.
"""


def js_object(src, marker):
    return json.loads(src[src.index("{", src.index(marker)):src.rindex("}") + 1])


def main():
    ds = {b["id"]: b for b in js_object((ROOT / "data" / "bills-2026.js").read_text(), "BILLS_2026")["bills"]}
    lg_src = (ROOT / "data" / "legiscan.js").read_text()
    lg = json.loads(lg_src[lg_src.index("= {") + 2: lg_src.rindex(";")])

    old = (ROOT / "data" / "bills.js").read_text()
    duties_block = old[old.index("duties: {"):old.index("},\n\n  families") + 2]
    duty_keys = set(re.findall(r'"([a-z-]+)":\s*\{ label:', duties_block))

    rows, dropped, problems = [], [], []
    for f in sorted(glob.glob(str(ROOT / "coding" / "coded" / "*.json"))):
        d = json.load(open(f))
        for e in d["entries"]:
            bid = e["id"]
            if e.get("duplicateOf"):
                dropped.append(f"{bid} (duplicate of {e['duplicateOf']})")
                continue
            enacted = ds.get(bid, {}).get("enacted", True) or lg.get(bid, {}).get("status") == "Passed"
            if not enacted:
                dropped.append(f"{bid} (not enacted)")
                continue
            for dk in e.get("duties", []):
                if dk not in duty_keys:
                    problems.append(f"{bid}: unknown duty '{dk}'")
            if e.get("family") not in FAM:
                problems.append(f"{bid}: unknown family '{e.get('family')}'")
            for k in e.get("params", {}):
                if k not in (e.get("sources") or {}):
                    problems.append(f"{bid}: param '{k}' has no source quote")
            rec = ds.get(bid, {})
            row = {
                "id": bid, "state": rec.get("state", bid[:2]),
                "name": rec.get("description", ""), "segment": e.get("segment"),
                "category": e["category"], "family": e["family"],
                "status": rec.get("status", "Enacted"), "appliesTo": e.get("appliesTo", ""),
                "duties": e.get("duties", []), "params": e.get("params", {}),
                "sources": dict(e.get("sources") or {}),
            }
            if e.get("exposure"):
                row["exposure"] = e["exposure"]
            if not row["segment"]:
                row.pop("segment")
            rows.append(row)

    if problems:
        print("VALIDATION FAILED:")
        for p in problems:
            print("  ", p)
        sys.exit(1)

    fam_counts = collections.Counter(r["family"] for r in rows)
    fams = ",\n".join(
        f'    "{k}": {{\n      label: {json.dumps(FAM[k][0])},\n      note: {json.dumps(FAM[k][1])}\n    }}'
        for k in FAM if fam_counts.get(k))
    bills = ",\n".join("    " + json.dumps(r, ensure_ascii=False) for r in rows)
    out = (HEADER + "\nwindow.MODEL_DATA = {\n\n"
           "  // Hours for the average AI model to satisfy each duty, wherever imposed.\n"
           "  // perRelease: true = the legal/eng work recurs with every model release\n"
           "  // (docs, provenance integration); the \"model releases\" control multiplies it.\n  "
           + duties_block + "\n\n  families: {\n" + fams + "\n  },\n\n  bills: [\n" + bills + "\n  ]\n};\n")
    (ROOT / "data" / "bills.js").write_text(out)
    print(f"data/bills.js: {len(rows)} entries from {len(glob.glob(str(ROOT / 'coding' / 'coded' / '*.json')))} coded bills")
    print("dropped:", "; ".join(dropped) or "none")


if __name__ == "__main__":
    main()
