#!/usr/bin/env python3
"""Distill the cached LegiScan bill records into data/legiscan.js.

The explorer overlays this on the working dataset: live status, official bill
page links, sponsors, floor votes, text versions, and substitution links
(NY-style companion bills). Rerun after any pipeline/legiscan.py fetch:

  python3 pipeline/enrich.py

Reads texts/tmp/legiscan/bill-*.json (the getBill cache) and texts/manifest/.
Data: LegiScan API, CC BY 4.0.
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATUS = {0: None, 1: "Introduced", 2: "Engrossed", 3: "Enrolled",
          4: "Passed", 5: "Vetoed", 6: "Failed"}
SAST = {1: "same as", 2: "similar to", 3: "replaced by", 4: "replaces",
        5: "crossfiled", 6: "enabling for", 7: "enabled by", 8: "related",
        9: "carry over"}


def slugify(bill_id):
    s = re.sub(r"([a-zA-Z])(\d)", r"\1-\2", bill_id)
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def display_number(n):
    # "HB0545" -> "HB 545", "A09487" -> "A 9487"
    return re.sub(r"([A-Za-z])0*(\d)", r"\1 \2", n, count=1)


def main():
    manifests = {}
    for p in (ROOT / "texts" / "manifest").glob("*.json"):
        m = json.loads(p.read_text())
        manifests[m["slug"]] = m

    out = {}
    for p in sorted((ROOT / "texts" / "tmp" / "legiscan").glob("bill-*.json")):
        b = json.loads(p.read_text())["bill"]
        # key by the dataset's own bill id (via the manifest, whose slug matches
        # the cache filename) — LegiScan formats numbers differently (CO
        # "HB 26-1139" vs "HB26-1139", ME LD vs HP, RI "H" vs "HB")
        stem = p.stem[len("bill-"):]                      # e.g. CO-hb-26-1139
        slug = stem[:2].lower() + "-" + stem[3:]
        m = manifests.get(slug, {})
        bill_id = m.get("id") or (b["state"] + " " + display_number(b["bill_number"]))
        floor = [v for v in b.get("votes", []) if v.get("total", 0) > 25]
        entry = {
            "status": STATUS.get(b.get("status")),
            "statusDate": b.get("status_date"),
            "title": b.get("title"),
            "stateLink": b.get("state_link"),
            "legiscanUrl": b.get("url"),
            "sponsors": [{"name": s["name"], "party": s.get("party"),
                          "district": s.get("district")} for s in b.get("sponsors", [])],
            "relations": [{"type": SAST.get(s.get("type_id"), "related"),
                           "bill": display_number(s["sast_bill_number"])}
                          for s in b.get("sasts", [])],
            "votes": [{"date": v["date"], "chamber": v.get("chamber"),
                       "yea": v["yea"], "nay": v["nay"], "passed": bool(v.get("passed"))}
                      for v in floor],
            "textVersions": [{"type": t["type"], "date": t["date"]} for t in b.get("texts", [])],
            "ourText": ({"version": m.get("version"), "chars": m.get("chars")}
                        if m.get("status") == "ok" else None),
        }
        out[bill_id] = {k: v for k, v in entry.items() if v not in (None, [], "")}

    js = ("// Generated by pipeline/enrich.py from the LegiScan API cache — do not edit.\n"
          "// Data: LegiScan (legiscan.com), CC BY 4.0.\n"
          "window.LEGISCAN = " + json.dumps(out, indent=1) + ";\n")
    (ROOT / "data" / "legiscan.js").write_text(js)
    print(f"data/legiscan.js: {len(out)} bills, {len(js) // 1024}kB")


if __name__ == "__main__":
    main()
